<?php
return [
    'show_warnings' => false,
    'orientation' => 'portrait',
    'defines' => [
        'font_dir' => storage_path('fonts/'),
        'font_cache' => storage_path('fonts/'),
        'temp_dir' => storage_path('temp/'),
        'chroot' => base_path(),
        'log_output_file' => null,
        'default_media_type' => 'screen',
        'default_paper_size' => 'a4',
        'default_font' => 'serif',
        'dpi' => 96,
        'font_height_ratio' => 1.1,
        'is_php_enabled' => false,
        'is_remote_enabled' => true,
        'is_html5_parser_enabled' => false,
        'is_font_subsetting_enabled' => false,
        'debug_png' => false,
        'debug_keep_temp' => false,
        'debug_css' => false,
        'debug_layout' => false,
        'debug_layout_lines' => true,
        'debug_layout_blocks' => true,
        'debug_layout_inline' => true,
        'debug_layout_padding_box' => true,
    ],
];
